### ISSUE TITLE
Unable to start the Python language server

### ISSUE THREAD

**Issue by Hazzard13** [lgeiger/ide-python#4]
Getting this error every time I start atom: 
> Unable to start the Python language server.
> This can occur if you do not have Python installed or if it is not in your path.
> 
> Make sure to install pyls by running:
> 
> pip install python-language-server  

I'm running the atom beta 1.21.0-beta0 x64, and pyls --help returns as expected.

**Comment by lgeiger** [comment]
I can reproduce this error. It looks like Atom doesn't preserve the env settings when not started from the command line.

For now starting Atom from the command line or configuring the `pyls` path to point to the absolut location should fix it.

**Comment by lgeiger** [comment]
Published `v0.1.1` with a fix for this issue: ff6df9e63c5064c23a77eed37181789e785b8923

**Comment by Hazzard13** [comment]
Man, thanks for the incredibly fast fix! Great work @lgeiger.

**Comment by AHolliday** [comment]
This issue still appears for me in version 0.8.0 of ide-python.  As @lgeiger said above, the issue doesn't occur if atom is launched from the command line, but does if launched any other way.  `pyls --help` gives the expected output.
